language: elixir
elixir:
  - 1.4.5
  - 1.5.1
  - 1.5.2
  - 1.6.0
otp_release:
  - 18.2.1
  - 18.3
  - 19.2
  - 19.3
  - 20.1
  - 20.2
matrix:
  include:
    - elixir: 1.5
      otp_release: 20.0
      env: MIX_ENV=test LOCKFILE=poison3
env:
  - MIX_ENV=test
script: mix coveralls.json
after_script:
  - bash <(curl -s https://codecov.io/bash)
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
