language: elixir
elixir:
  - 1.4.5
  - 1.5.2
  - 1.5.3
  - 1.6.3
  - 1.6.4
otp_release:
  - 18.3
  - 19.3
  - 20.2
matrix:
  exclude:
    - elixir: 1.6.3
      otp_release: 18.3
    - elixir: 1.6.4
      otp_release: 18.3
  include:
    - elixir: 1.5.3
      otp_release: 20.2
      env: MIX_ENV=test LOCKFILE=poison3
    - elixir: 1.6.4
      otp_release: 20.2
      install: skip
      script: mix format --check-formatted --dry-run
      after_script: skip
env:
  - MIX_ENV=test
script: mix coveralls.json
after_script:
  - bash <(curl -s https://codecov.io/bash)
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
